version: "3.3"
services:
  nginx:
    image: nginx:1-alpine
    ports:
      - 8080:80
    volumes:
      - ./out:/usr/share/nginx/html:ro
    depends_on:
      - api
  api:
    image: 7010/json-server
    ports:
      - 3000:3000
    volumes:
      - ./tools/db.json:/db.json
